# Exported from Render on 2025-04-29T20:50:02Z
services:
- type: web
  name: sa17-act1-inniang
  runtime: ruby
  repo: https://github.com/um-202510-comp-3081/sa17-act1-inniang
  plan: free
  envVars:
  - key: WEB_CONCURRENCY
    sync: false
  - key: RAILS_ENV
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
 

    


