
 
services:
  - type: web
    name: sa17-act1-inniang
    runtime: ruby
    plan: free
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: work-postgres   # <-- update this
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2



