databases:
  - name: work-postgres
    plan: free

services:
  - type: web
    name: work-rails-app
    runtime: ruby
    plan: free
    region: oregon  # Options: oregon (default), ohio, virginia, frankfurt, singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: work-postgres
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"

